### ISSUE TITLE
Utwory

### ISSUE THREAD

**Issue by Gatki** [AdrianEddy/AIMPYouTube#11]
Witam, plugin przestał działać przeskakuje przez utwory.

**Comment by TDSrock** [comment]
Several tracks with adds are being skipped again. If I am not mistaken it's to do with the decoder.

**Comment by Gatki** [comment]
It`s works.

**Comment by TDSrock** [comment]
Negative:
https://i.gyazo.com/eedaa1ef6eb5ea2477534d2f5e0b3ef5.mp4

**Comment by Gatki** [comment]
Update for 1.0 RC6. http://i.imgur.com/BTm7Cup.png

http://i.imgur.com/7s1DFfK.png

**Comment by TDSrock** [comment]
That is the version I am running yet it still skips the first 9 songs of this playlist.

![playlist](https://i.gyazo.com/8c2cb6d57eed4f5c55f35971d211fbd0.png)

**Comment by bafsar** [comment]
Like TDSrock's playlists, my playlists do the same.

**Comment by TDSrock** [comment]
Further info on this error.

Every-time AIMP gets an update it seems to fix itself for exactly one track play. Any future attempts at playing the same track will fail. This does not happen to all files. I believe it happens to youtube videos intended to play ads alongside them.

**Comment by TDSrock** [comment]
Looking into it further yet again. Seems like a local storage issue now. On reboot all songs are played properly again(as far as I have tested, which is about 20 songs on the list). I expect this to be a 1 time fix again(so once I try to play it again later it won't work again) Will update.

**Comment by AdrianEddy** [comment]
Fixed in  48878ab and version [v1.1](https://github.com/AdrianEddy/AIMPYouTube/releases)
