### ISSUE TITLE
I tried to play, it refused.

### ISSUE THREAD

**Issue by Ayria** [AdrianEddy/AIMPYouTube#14]
I tried with several youtube links. I got this every time.
Am I doing something wrong maybe?

File: youtube://OIh3nO6-V_A/Metallica - Whiskey in the jar.mp4
Code: -1 (FFFFFFFF)
Message: Unknown Error
-------------------------
HTTP/1.1 403 Forbidden
Last-Modified: Wed, 02 May 2007 10:26:10 GMT
Content-Type: text/plain
Content-Length: 0
Connection: close
X-Content-Type-Options: nosniff
Date: Wed, 16 Aug 2017 19:21:51 GMT
Server: gvs 1.0

**Comment by Titanic4** [comment]
I've got similar issue as well - I think it's caused by daily quota being exceeded or something like that.

**Comment by T1mL3arn** [comment]
Have the same.

**Comment by AdrianEddy** [comment]
Fixed in latest commits, binary release will be updated soon
