### ISSUE TITLE
Optional renamed playlist not work

### ISSUE THREAD

**Issue by Gelo3D** [AdrianEddy/AIMPYouTube#19]
If i give a custom name for my playlisty in : 

![obraz](https://user-images.githubusercontent.com/15075411/35564037-17393568-05b9-11e8-9347-c5f704237e6e.png)

I grab this : 
![obraz](https://user-images.githubusercontent.com/15075411/35564054-2750ed7e-05b9-11e8-90ea-bc72e9f224d0.png)

This is aimp default playlists name. 
Like if you add folder called ABSOUL your playlist name is ABSOUL

**Comment by AdrianEddy** [comment]
Fixed in  48878ab and version [v1.1](https://github.com/AdrianEddy/AIMPYouTube/releases)
