### ISSUE TITLE
How can I download songs instead of saving it in buffer?

### ISSUE THREAD

**Issue by Ssshivaaa** [AdrianEddy/AIMPYouTube#23]
Hello! How can I download songs instead of keeping it in buffer? I tracked aimp activity while using your plugin with process explorer and it showed that files are written to device\afd. What can I do in your code to download the song and if it's already downloaded then don't download it and just load from directory?

**Comment by AdrianEddy** [comment]
Hi!
The plugin itself doesn't handle any writing or downloads, that's handled by AIMP itself. This plugin only supplies the URL for AIMP to play. 
You could possibly modify this plugin to first download the youtube movie and pass the downloaded file to AIMP, but then you'd have to wait for the download to complete before playing anything so I don't think it's very useful.

**Comment by AdrianEddy** [comment]
AIMP4 also supports drag & drop, so you can add the song to the playlist and drag it to your desktop, and it will download that movie
