### ISSUE TITLE
Plugin not found my account after youtube granted access

### ISSUE THREAD

**Issue by objque** [AdrianEddy/AIMPYouTube#3]
Hi,

I granted access to plugin (youtube say: 'now can close tab') and plugin not recognize me.
Can i pass access_token manually?

I use win7, chrome(50), aimp4.
Thanks.

**Comment by AdrianEddy** [comment]
Hi, It looks like it is the problem with the new AIMP version. It works in v3.60 and in v4.10 alpha (available only for developers). I already notified the AIMP author and we'll have to wait for his response
