### ISSUE TITLE
Errors on connection drop 

### ISSUE THREAD

**Issue by alexei-petru** [AdrianEddy/AIMPYouTube#37]
It is an amazing and useful plugin, but when my internet drops I have this stack of errors, I suppose is not a hard problem to fix.
In my opinion, it is better to not see an error and just to switch to the next play.
If someone can help with a fix or with a hint how to fix this,  it will be very nice and useful. 
![image](https://user-images.githubusercontent.com/76633311/213463918-98ff9fc7-79ca-44ea-9fe2-e55a7a79e53f.png)

**Comment by cloewen8** [comment]
I believe my pull request #42 would resolve this
