### ISSUE TITLE
Can`t seek fragment when not loaded / cached. [Work / Comment] 

### ISSUE THREAD

**Issue by Gelo3D** [AdrianEddy/AIMPYouTube#5]
> Can`t seek fragment when not loaded / cached.
> Sometime people wonna seek unloaded fragment eg. from 1hour music :D 
> Your plugin doesnt do it. 
I can seek but i must press mouse button 3-4x :D 
But its not very big problem ;p 

General plugin very good, you get really respect from me ! 
Good work, if i search some request / bugs i 'call' to You :P

**Comment by AdrianEddy** [comment]
I can't do anything about it, the playback itself is controlled by AIMP. This plugin only provides an URL for AIMP to play
