### ISSUE TITLE
Youtube live streams don't work

### ISSUE THREAD

**Issue by Lubieerror** [AdrianEddy/AIMPYouTube#9]
Youtube music live streams ("radios") growing popularity so I think it would be nice and I and more people for sure would if you add support of that.
It would be nice even if you just add message that plugin don't support it (now it don't throw any errors, nothing showing up etc.).

**Comment by truer0man** [comment]
Confirmed, live streams are not working. Other functions works just fine. Browsers consume too much RAM on PC, so i'd like to get a possibility play streams on AIMP. 
Anyway, nice job, Adrian.

**Comment by T1mL3arn** [comment]
For now there is a fork which supports livestreams. Check it https://github.com/jaryn-kubik/AIMPYouTube/releases/tag/1.1.3 .

**Comment by AdrianEddy** [comment]
Fixed in v1.3
